apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  # This assumes tls-secret exists.
  - secretName: staging-secret
  backend:
    serviceName: example
    servicePort: 40010
---
apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
    environment: staging
spec:
  type: NodePort
  ports:
  - name: example-http
    port: 40010
    targetPort: example-http
  selector:
    app: example
    environment: staging
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 120%
      maxUnavailable: 20% 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example
        environment: staging
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.5
        ports:
        - name: example-http
          containerPort: 40010
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/ssl-redirect.conf
          name: example
          subPath: nginx.conf
      - name: example-app
        image: us.gcr.io/some-path-to-somecontainer:latest
        command: ['blah', '-C', 'config/foo.rb']
        ports:
        - name: example-https
          containerPort: 9292
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - mountPath: /mgt/example/adminservice.yml
          name: example
          subPath: adminservice.yml
        - mountPath: /mgt/example/amazon_s3.yml
          name: example
          subPath: amazon_s3.yml
        - mountPath: /mgt/example/bunny.yml
          name: example
          subPath: bunny.yml
        - mountPath: /mgt/example/consumers.yml
          name: example
          subPath: consumers.yml
        - mountPath: /mgt/example/database.yml
          name: example
          subPath: database.yml
        - mountPath: /mgt/example/newrelic.yml
          name: example
          subPath: newrelic.yml
        - mountPath: /mgt/example/service.rb
          name: example
          subPath: service.rb
        - mountPath: /mgt/example/redis.yml
          name: example
          subPath: redis.yml
      - name: memcached
        image: memcached:1.5.1
        command: ["/usr/local/bin/memcached", "-m", "1024", "-v"]
        ports:
        - name: example-memcache
          containerPort: 11211
        resources:
          limits:
            cpu: "500m"
            memory: "1280Mi"
          requests:
            cpu: "100m"
            memory: "1024Mi"
      volumes:
      - name: example
        configMap:
          name: example
